### PR TITLE
ADBDEV-6046: Fix gprestore check helper error when resize restore

### PR DESCRIPTION
**Pull request by RekGRpth**
Fix gprestore check helper error when resize restore

If helper terminates with a fatal error during a resize restore, the main
gprestore process does not check existing of error file, which is generated by
helpers, and continues to try restoring tables, waits 300 seconds when the next
pipe is created. This patch adds checking error files on helper before each
COPY commands and also adds checking error files during waiting timeout.

### CODE REVIEW

**Comment by bimboterminator1** [comment]
What's wrong with the tests?

**Comment by RekGRpth** [comment]
> What's wrong with the tests?

Interesting, previous run (before merging) was successful...

**Comment by red1452** [comment]
I think, description must be rewrited:
```
If helper terminates with a fatal error during a resize restore, the main gprestore process does not check existing of error file, which is generated by helpers, and continues to try restoring tables, waits 300  seconds when the next pipe is created. This patch adds checking error files on helper before each COPY commands and also adds checking error files during waiting timeout.
```

**Comment by RekGRpth** [comment]
> I think, description must be rewrited:
> 
> ```
> If helper terminates with a fatal error during a resize restore, the main
> gprestore process does not check existing of error file, which is generated by
> helpers, and continues to try restoring tables, waits 300  seconds when the next
> pipe is created. This patch adds checking error files on helper before each COPY
> commands and also adds checking error files during waiting timeout.
> ```

rewritten

**Review by red1452 — APPROVED** [review]

**Pull request merged**
