### PR TITLE
ADBDEV-4874: gpbackup e2e test suite hangs

### PR DESCRIPTION
**Pull request by RekGRpth**
Commit 6f71685 introduced hang errors.
I found that tests sometimes freeze
```sh
ginkgo -r --keep-going --randomize-suites --randomize-all --no-color --poll-progress-after=0s -vv --timeout=3h --poll-progress-after=0s end_to_end -- --custom_backup_dir /home/gpbackup --ginkgo.focus 'runs gprestore with copy-queue-size and sends a SIGTERM to ensure cleanup functions successfully'

------------------------------
Signal handler tests
/home/src/gpbackup/end_to_end/signal_handler_test.go:14
  SIGTERM
  /home/src/gpbackup/end_to_end/signal_handler_test.go:249
    runs gprestore with copy-queue-size and sends a SIGTERM to ensure cleanup functions successfully
    /home/src/gpbackup/end_to_end/signal_handler_test.go:441
  > Enter [BeforeEach] Signal handler tests - /home/src/gpbackup/end_to_end/signal_handler_test.go:15 @ 01/23/24 12:53:04.392
  < Exit [BeforeEach] Signal handler tests - /home/src/gpbackup/end_to_end/signal_handler_test.go:15 @ 01/23/24 12:53:20.846 (16.454s)
  > Enter [It] runs gprestore with copy-queue-size and sends a SIGTERM to ensure cleanup functions successfully - /home/src/gpbackup/end_to_end/signal_handler_test.go:441 @ 01/23/24 12:53:20.846
  [FAILED] Timed out after 10.001s.
  Expected
      <string>: postgres  611875  611861  1 12:53 pts/0    00:00:00 /usr/local/bin/gpbackup_helper --restore-agent --toc-file /home/gpbackup/temp4144456127/demoDataDir1/backups/20240123/20240123125320/gpbackup_1_20240123125320_toc.yaml --oid-file /home/.data/6/dbfast2/demoDataDir1/gpbackup_1_20240123125320_oid_611663 --pipe-file /home/.data/6/dbfast2/demoDataDir1/gpbackup_1_20240123125320_pipe_611663 --data-file /home/gpbackup/temp4144456127/demoDataDir1/backups/20240123/20240123125320/gpbackup_1_20240123125320.gz --content 1 --compression-type gzip --single-data-file --copy-queue-size 5 --replication-file /home/.data/6/dbfast2/demoDataDir1/gpbackup_1_20240123125320_replicated_oid_611663\npostgres  611876  611864  1 12:53 pts/0    00:00:00 /usr/local/bin/gpbackup_helper --restore-agent --toc-file /home/gpbackup/temp4144456127/demoDataDir2/backups/20240123/20240123125320/gpbackup_2_20240123125320_toc.yaml --oid-file /home/.data/6/dbfast3/demoDataDir2/gpbackup_2_20240123125320_oid_611663 --pipe-file /home/.data/6/dbfast3/demoDataDir2/gpbackup_2_20240123125320_pipe_611663 --data-file /home/gpbackup/temp4144456127/demoDataDir2/backups/20240123/20240123125320/gpbackup_2_20240123125320.gz --content 2 --compression-type gzip --single-data-file --copy-queue-size 5 --replication-file /home/.data/6/dbfast3/demoDataDir2/gpbackup_2_20240123125320_replicated_oid_611663
  to equal
      <string>: 
  In [It] at: /home/src/gpbackup/end_to_end/end_to_end_suite_test.go:286 @ 01/23/24 12:53:34.874
  < Exit [It] runs gprestore with copy-queue-size and sends a SIGTERM to ensure cleanup functions successfully - /home/src/gpbackup/end_to_end/signal_handler_test.go:441 @ 01/23/24 12:53:34.874 (14.029s)
  > Enter [AfterEach] Signal handler tests - /home/src/gpbackup/end_to_end/signal_handler_test.go:19 @ 01/23/24 12:53:34.874
  < Exit [AfterEach] Signal handler tests - /home/src/gpbackup/end_to_end/signal_handler_test.go:19 @ 01/23/24 12:53:34.9 (25ms)

  Attempt #1 Failed.  Retrying ↺ @ 01/23/24 12:53:34.9

  > Enter [BeforeEach] Signal handler tests - /home/src/gpbackup/end_to_end/signal_handler_test.go:15 @ 01/23/24 12:53:34.9
```
In the upstream they found another error described in the [PR](https://github.com/greenplum-db/gpbackup/pull/752).

I applied upstream commit ab6458944aee9182931d1abd57f12c5bfc84836c.

### CODE REVIEW

**Review by dnskvlnk — DISMISSED** [review]

**Review by red1452 — DISMISSED** [review]

**Review by red1452 — COMMENTED** [review]
1) Add description for each commit, why do you revert it.
2) Partial reverts of three commits in one is bad idea.
3) Can you fix the problem without reverting commits?

**Comment by RekGRpth** [comment]
> Add description for each commit, why do you revert it.

I didn't decide to check back each commit individually. The main thing here is that the upstream decided to do this.

> Partial reverts of three commits in one is bad idea.

Unfortunately it is so.



> Can you fix the problem without reverting commits?

I tried, but it doesn't make sense anymore.

**Review by red1452 — COMMENTED** [review]
Original commit contains changes in file `go.sum`. At your backport there are not this changes. Why do you remove this changes? Lines, which were removed at original patch there are at [1.30.2-sync](https://github.com/arenadata/gpbackup/blob/6f71685012b4e78ee3e49167ac07d1c2c28c37e3/go.sum#L129-L120).

**Review by red1452 — DISMISSED** [review]

**Comment by Stolb27** [comment]
Merged through 80d2db4

**Pull request closed without merging**
